Remove explicit type definition
It's not necessary anymore since apache/flink@ab84707 commit removes it.
It'll raise `TypeError`:
```
TypeError: flat_map() takes 2 positional arguments but 3 were given
```